"""
Parse the HTML reports generated by the docu-jarvis Go binary.

The HTML template (internal/report/report.go) uses:
  - .kv .key / .kv .val  →  key/value stats
  - .section h3          →  section headings
  - .section .body       →  AI narrative content
  - .badge               →  severity badges
  - .finding             →  individual security findings
"""
from __future__ import annotations

import logging
import re
from typing import Any

from bs4 import BeautifulSoup, Tag

logger = logging.getLogger(__name__)


def _text(el: Tag | None) -> str:
    if el is None:
        return ""
    return el.get_text(separator=" ", strip=True)


def _kv_map(soup: BeautifulSoup) -> dict[str, str]:
    """Extract all .kv rows into a dict keyed by the label text."""
    result: dict[str, str] = {}
    for row in soup.select(".kv"):
        key_el = row.select_one(".key")
        val_el = row.select_one(".val")
        if key_el and val_el:
            key = _text(key_el).lower().replace(" ", "_").rstrip(":")
            result[key] = _text(val_el)
    return result


def _section_map(soup: BeautifulSoup) -> dict[str, str]:
    """Extract all .section blocks keyed by their heading."""
    result: dict[str, str] = {}
    for sec in soup.select(".section"):
        heading = sec.select_one("h3")
        body = sec.select_one(".body")
        if heading and body:
            key = _text(heading).lower().replace(" ", "_").replace("/", "_")
            result[key] = _text(body)
    return result


def _to_int(v: str | None, default: int = 0) -> int:
    if not v:
        return default
    m = re.search(r"\d+", v)
    return int(m.group()) if m else default


# ── Security ──────────────────────────────────────────────────────────────────

def _parse_security(soup: BeautifulSoup, raw_html: str) -> dict[str, Any]:
    kv = _kv_map(soup)

    findings_data: list[dict] = []
    for idx, f_el in enumerate(soup.select(".finding")):
        # Each finding card has kv rows inside it
        fkv = {}
        for row in f_el.select(".kv"):
            k_el = row.select_one(".key")
            v_el = row.select_one(".val")
            if k_el and v_el:
                k = _text(k_el).lower().replace(" ", "_").rstrip(":")
                fkv[k] = _text(v_el)

        badge_el = f_el.select_one(".badge")
        severity = _text(badge_el).upper() if badge_el else fkv.get("severity", "LOW")

        snippet_el = f_el.select_one("pre, code")
        snippet = _text(snippet_el) if snippet_el else ""

        # AI sections inside the finding
        sections: dict[str, str] = {}
        for sec in f_el.select(".section"):
            h = sec.select_one("h3")
            b = sec.select_one(".body")
            if h and b:
                sections[_text(h).lower()] = _text(b)

        findings_data.append(
            {
                "id": fkv.get("id", f"finding-{idx}"),
                "rule_id": fkv.get("rule", fkv.get("rule_id", "unknown")),
                "category": fkv.get("owasp", fkv.get("category", "")),
                "severity": severity,
                "title": fkv.get("title", ""),
                "file": fkv.get("file", ""),
                "line": _to_int(fkv.get("line")),
                "snippet": snippet,
                "description": sections.get("description", fkv.get("description", "")),
                "explanation": sections.get("explanation", ""),
                "why_dangerous": sections.get("why dangerous", sections.get("why_dangerous", "")),
                "how_to_fix": sections.get("how to fix", sections.get("how_to_fix", "")),
                "detected_by": fkv.get("detected_by", "pattern"),
            }
        )

    critical = _to_int(kv.get("critical"))
    high = _to_int(kv.get("high"))
    medium = _to_int(kv.get("medium"))
    low = _to_int(kv.get("low"))
    total = critical + high + medium + low or _to_int(kv.get("findings"))

    return {
        "files_scanned": _to_int(kv.get("files_scanned")),
        "lines_scanned": _to_int(kv.get("lines_scanned")),
        "scan_duration_ms": _to_int(kv.get("scan_time")),
        "total": total,
        "critical": critical,
        "high": high,
        "medium": medium,
        "low": low,
        "findings": findings_data,
        "raw_html": raw_html,
    }


# ── Impact ────────────────────────────────────────────────────────────────────

def _parse_impact(soup: BeautifulSoup, raw_html: str) -> dict[str, Any]:
    kv = _kv_map(soup)
    sections = _section_map(soup)

    return {
        "risk_level": kv.get("risk_level", kv.get("risk", "UNKNOWN")).upper(),
        "risk_score": _to_int(kv.get("risk_score")),
        "direct_callers": _to_int(kv.get("direct_callers")),
        "total_callers": _to_int(kv.get("total_callers")),
        "max_graph_depth": _to_int(kv.get("max_graph_depth")),
        "affected_packages": _to_int(kv.get("affected_pkgs", kv.get("dependent_pkgs"))),
        "critical_systems": [
            s.strip()
            for s in kv.get("critical_systems", "").split(",")
            if s.strip()
        ],
        "has_tests": "present" in kv.get("test_coverage", "").lower(),
        "what_changing": sections.get("what_this_code_does", ""),
        "direct_impact": sections.get("direct_impact__depth_1_callers_", sections.get("direct_impact", "")),
        "indirect_impact": sections.get("indirect___transitive_impact", sections.get("indirect_impact", "")),
        "critical_paths": sections.get("critical_call_chains", sections.get("critical_paths", "")),
        "safety_net": sections.get("safety_net___circuit_breakers", sections.get("safety_net", "")),
        "risk_assessment": sections.get("risk_assessment", ""),
        "testing_strategy": sections.get("testing_strategy", ""),
        "next_steps": sections.get("recommended_next_steps", sections.get("next_steps", "")),
        "unknowns": sections.get("unknowns___gaps", sections.get("unknowns", "")),
        "raw_html": raw_html,
    }


# ── Why ───────────────────────────────────────────────────────────────────────

def _parse_why(soup: BeautifulSoup, raw_html: str) -> dict[str, Any]:
    kv = _kv_map(soup)
    sections = _section_map(soup)

    return {
        "classification": kv.get("classification", ""),
        "confidence": kv.get("confidence", ""),
        "confidence_score": _to_int(kv.get("confidence_score")),
        "still_needed": kv.get("still_needed", "UNCERTAIN").upper(),
        "risk_level": kv.get("removal_risk", kv.get("risk_level", "MEDIUM")).upper(),
        "what_it_does": sections.get("what_it_does", ""),
        "most_likely_reason": kv.get("most_likely_reason", ""),
        "evidence_summary": sections.get("evidence_summary", ""),
        "still_needed_reason": sections.get("still_needed_reason", sections.get("still_needed", "")),
        "what_breaks": sections.get("what_breaks_if_removed", sections.get("what_breaks", "")),
        "next_steps": sections.get("recommended_next_steps", sections.get("next_steps", "")),
        "unknowns": sections.get("unknowns", ""),
        "total_commits": _to_int(kv.get("commits_analysed", kv.get("total_commits"))),
        "history_days": _to_int(kv.get("history_days")),
        "raw_html": raw_html,
    }


# ── Public API ────────────────────────────────────────────────────────────────

def parse_report(html_content: str, mode: str) -> dict[str, Any]:
    soup = BeautifulSoup(html_content, "html.parser")

    if mode == "security":
        return _parse_security(soup, html_content)
    if mode == "impact":
        return _parse_impact(soup, html_content)
    if mode == "why":
        return _parse_why(soup, html_content)

    # fallback — return raw HTML for the frontend to embed
    return {"raw_html": html_content}
